# Build pipeline

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  demands: npm

steps:
- task: NodeTool@0
  displayName: 'Use Node 8.x'
  inputs:
    versionSpec: 8.x

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    Contents: |
     **
     !node_modules/**
     !dist/**
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
